// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // return web;
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for windows - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //         'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //         'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyBfxgNJ-3amxh54Sf3K_965QQJxDpnRHho',
  //   appId: '1:742809958627:web:42781506691a4910842dd6',
  //   messagingSenderId: '742809958627',
  //   projectId: 'fir-2203-2023',
  //   authDomain: 'fir-2203-2023.firebaseapp.com',
  //   storageBucket: 'fir-2203-2023.appspot.com',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMThASQbWCjQwdEKp4duHpt3dqxeY2lSE',
    appId: '1:609678391580:android:b83705b29fde182ba1e2d9',
    messagingSenderId: '609678391580',
    projectId: 'flutter-firebase-project-bd961',
    storageBucket: 'flutter-firebase-project-bd961.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyAkFqdTw8CZleMQTbdf08nfFJ-x2iWebV0',
  //   appId: '1:742809958627:ios:ad64e91d700218ad842dd6',
  //   messagingSenderId: '742809958627',
  //   projectId: 'fir-2203-2023',
  //   storageBucket: 'fir-2203-2023.appspot.com',
  //   iosBundleId: 'com.example.futures',
  // );
  //
  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyAkFqdTw8CZleMQTbdf08nfFJ-x2iWebV0',
  //   appId: '1:742809958627:ios:2944321c3e5b678d842dd6',
  //   messagingSenderId: '742809958627',
  //   projectId: 'fir-2203-2023',
  //   storageBucket: 'fir-2203-2023.appspot.com',
  //   iosBundleId: 'com.example.futures.RunnerTests',
  // );
}
